version: '3.8'

services:
  backend:
    build: .
    container_name: zonaquintas-backend
    restart: always
    ports:
      - "8009:8000"
    env_file:
      - .env
    environment:
      # Activamos el modo produccion para leer la carpeta absoluta
      - ENV=production
      - DOMAIN_URL=https://zonaquintas.com/MdpuF8KsXiRArNlHtl6pXO2XyLSJMTQ8_Zonaquintas/api/images
    volumes:
      # Mapeamos la carpeta de tu VPS a la carpeta que lee el contenedor
      - /home/iweb/zonaquintas/data/images:/home/iweb/zonaquintas/data/images
